#!/bin/bash

SYSTEMS="debian6 debian7 debian8 debian9 debian10 debian11 ubuntu10 ubuntu12 ubuntu13_04 ubuntu14 ubuntu15_10 ubuntu16 ubuntu18 ubuntu20 ubuntu22 rhel5 rhel6 rhel7 rhel8 rhel9 sles11 sles12 sles15 slackware14"

if [ -z "$1" ];
then
  echo "Usage $0 <rudder-version>"
  exit 1
fi
version="$1"

mkdir -p inventories
conf=$(mktemp)

for s in ${SYSTEMS}
do
  echo '{ "default":{}, "agent": { "rudder-setup": "agent", "system": "'"${s}"'", "save-inventory": "true" }}' > platforms/inventories.json
  echo "-- Inventory of ${s} --"
  ./rtf platform setup inventories "${version}"
  vagrant ssh-config inventories_agent > ${conf}
  sed -i '$ i\  PubkeyAcceptedKeyTypes +ssh-rsa' ${conf}
  sed -i '$ i\  HostKeyAlgorithms +ssh-rsa' ${conf}
  scp -F "${conf}" inventories_agent:/tmp/*.ocs inventories/
  ./rtf platform destroy inventories
done
rm "${conf}"
