# -*- mode: ruby -*-
# vi: set ft=ruby :

#####################################################################################
# Copyright 2012 Normation SAS
#####################################################################################
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, Version 3.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#####################################################################################

def configure(config, name, os, memory, ip, hostname, parameters, forward)
  config.vm.define (name).to_sym do |server_config|
    server_config.vm.box = os[:name]
    server_config.vm.box_url = os[:url]
    server_config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", memory]
    end
    if forward != 0 then
      server_config.vm.network :forwarded_port, guest: 80, host: (forward*100+80)
      server_config.vm.network :forwarded_port, guest: 443, host: (forward*100+81)
    end
    server_config.vm.network :private_network, ip: ip
    server_config.vm.hostname = hostname
    command  = "/vagrant/scripts/cleanbox " + (forward-40).to_s + "\n"
    command += "/vagrant/scripts/rudder-setup " + parameters + "\n"
    command += "/vagrant/scripts/create-token\n"
    server_config.vm.provision :shell, :inline => command
  end
end


Vagrant.configure("2") do |config|

  centos6 = {
    :name   => "centos6",
    :url    => "http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.3-x86_64-v20130101.box",
    :server => "server_centos6.sh",
  }

  centos5 = {
    :name   => "centos5",
    :url    => "http://puppet-vagrant-boxes.puppetlabs.com/centos-59-x64-vbox4210-nocm.box",
  }

  oracle6 = {
    :name   => "oracle6",
    :url    => "https://storage.us2.oraclecloud.com/v1/istoilis-istoilis/vagrant/oel65-32.box",
    :server => "server_centos6.sh",
  }

  debian6 = {
    :name   => "debian6",
    :url    => "http://dl.dropbox.com/u/937870/VMs/squeeze64.box",
    :server => "server.sh",
  }

  debian7 = {
    :name   => "debian7",
    :url    => "https://dl.dropboxusercontent.com/u/197673519/debian-7.2.0.box",
    :server => "server.sh",
  }

  sles11 = {
    :name   => "sles11",
    :url    => "http://puppetlabs.s3.amazonaws.com/pub/sles11sp1_64.box",
    :server => "server_sles11.sh",
  }

  ubuntu12_10 = {
    :name   => "ubuntu12",
    :url    => "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.10_chef-provisionerless.box",
    :server => "server_ubuntu.sh",
  }

  ubuntu14_04  = {
    :name   => "ubuntu14",
    :url    => "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box",
  }
  
  solaris11 = {
    :name   => "solaris11",
    :url    => "http://www.benden.us/vagrant/solaris-11.1.box"
  }

### AUTOGENERATED FOR PLATFORM test.json
configure(config, 'test_agent2', centos6, "256", "192.168.43.11", "agent2", "setup_agent 3.0", 0)
configure(config, 'test_agent1', centos6, "256", "192.168.42.11", "agent1", "setup_agent 3.0", 0)
configure(config, 'test_server', centos6, "1536", "192.168.42.10", "server", "setup_server 3.0", 80)
### END OF AUTOGENERATION FOR test.json

### AUTOGENERATED FOR PLATFORM sles
configure(config, 'sles_server', sles11, '1536', '192.168.41.2', 'server', 'setup_server 2.10-nightly', 81)
configure(config, 'sles_agent1', sles11, '256', '192.168.41.3', 'agent1', 'setup_agent 2.10-nightly', 0)
### END OF AUTOGENERATION FOR sles

### AUTOGEN TAG

end


