# -*- mode: ruby -*-
# vi: set ft=ruby :

#####################################################################################
# Copyright 2012 Normation SAS
#####################################################################################
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, Version 3.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#####################################################################################

def configure(config, os, pf_name, pf_id,  host_id, version)
  # Parameters
  if host_id == 0 then
    host_name = "server"
    memory = "1536"
  else
    host_name = "agent" + host_id.to_s
    memory = "256"
  end
  name = pf_name + "_" + host_name
  net = "192.168." + (pf_id+40).to_s
  ip = net + "." + (host_id+2).to_s
  forward = 100*(80+pf_id)+80
  command  = "/vagrant/scripts/cleanbox " + net + "\n"
  if host_id == 0 then
    command += "export ALLOWEDNETWORK=" + net + ".0/24\n"
    command += "/vagrant/scripts/rudder-setup setup_server " + version + "\n"
    command += "/vagrant/scripts/create-token\n"
  else
    command += "/vagrant/scripts/rudder-setup setup_agent " + version + "\n"
  end

  # Configure
  config.vm.define (name).to_sym do |server_config|
    server_config.vm.box = os[:name]
    server_config.vm.box_url = os[:url]
    server_config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", memory]
    end
    if host_id == 0 then
      server_config.vm.network :forwarded_port, guest: 80, host: forward
      server_config.vm.network :forwarded_port, guest: 443, host: forward+1
    end
    server_config.vm.network :private_network, ip: ip
    server_config.vm.hostname = host_name
    server_config.vm.provision :shell, :inline => command
  end
end


Vagrant.configure("2") do |config|

  centos6 = {
    :name   => "centos6",
    :url    => "http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.3-x86_64-v20130101.box",
    :server => "server_centos6.sh",
  }

  centos5 = {
    :name   => "centos5",
    :url    => "http://puppet-vagrant-boxes.puppetlabs.com/centos-59-x64-vbox4210-nocm.box",
  }

  oracle6 = {
    :name   => "oracle6",
    :url    => "https://storage.us2.oraclecloud.com/v1/istoilis-istoilis/vagrant/oel65-32.box",
    :server => "server_centos6.sh",
  }

  debian6 = {
    :name   => "debian6",
    :url    => "http://dl.dropbox.com/u/937870/VMs/squeeze64.box",
    :server => "server.sh",
  }

  debian7 = {
    :name   => "debian7",
    :url    => "https://dl.dropboxusercontent.com/u/197673519/debian-7.2.0.box",
    :server => "server.sh",
  }

  sles11 = {
    :name   => "sles11",
    :url    => "http://puppetlabs.s3.amazonaws.com/pub/sles11sp1_64.box",
    :server => "server_sles11.sh",
  }

  ubuntu12_10 = {
    :name   => "ubuntu12",
    :url    => "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.10_chef-provisionerless.box",
    :server => "server_ubuntu.sh",
  }

  ubuntu14_04  = {
    :name   => "ubuntu14",
    :url    => "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box",
  }
  
  solaris11 = {
    :name   => "solaris11",
    :url    => "http://www.benden.us/vagrant/solaris-11.1.box"
  }


### AUTOGENERATED FOR PLATFORM test (0)
configure(config, sles11, 'test', 0, 0, '2.10-nightly')
configure(config, sles11, 'test', 0, 1, '2.10-nightly')
### END OF AUTOGENERATION FOR sles


### AUTOGENERATED FOR PLATFORM sles (2)
configure(config, sles11, 'sles', 2, 0, 'ci/2.11.6-4')
configure(config, sles11, 'sles', 2, 1, 'ci/2.11.6-4')
### END OF AUTOGENERATION FOR sles

### AUTOGENERATED FOR PLATFORM centos (3)
configure(config, centos6, 'centos', 3, 0, 'ci/2.11.6-4')
configure(config, centos6, 'centos', 3, 1, 'ci/2.11.6-4')
### END OF AUTOGENERATION FOR centos

### AUTOGENERATED FOR PLATFORM debian (3)
configure(config, debian7, 'debian', 4, 0, 'ci/2.11.6-4')
configure(config, debian7, 'debian', 4, 1, 'ci/2.11.6-4')
### END OF AUTOGENERATION FOR debian

### AUTOGEN TAG

end


