#!/bin/bash

test_description="Test OS support in fusion inventory"

. sharness.sh

test_fusion_os() {
	rm -rf /tmp/x
	mkdir /tmp/x
	/opt/rudder/bin/run-inventory --local=/tmp/x
	sed -ne '/<HARDWARE>/,/<.HARDWARE>/p' /tmp/x/* | grep OSNAME | grep -i $TEST_SYSTEM
}

test_expect_success "OS supported by fusion" "
    test_fusion_os
"

test_done
