#!/bin/bash
set -x

PLATFORM_NAME=$1
TAG=$2

DIR=$(dirname "${BASH_SOURCE[0]}")
DST=${DIR}/../external_files/${PLATFORM_NAME}
mkdir -p ${DST}

if [ ! -d "${DST}" ] ; then
  rm -rf $DST/ncf*
fi
# Get correct ncf branch
git clone -b branches/rudder/${TAG} --single-branch https://github.com/Normation/ncf.git ${DST}/ncf
wget -O ${DST}/ncf-setup https://repository.rudder.io/tools/ncf-setup
wget -O ${DST}/rudder_apt_key.pub "https://repository.rudder.io/apt/rudder_apt_key.pub"
wget -O ${DST}/rudder_rpm_key.pub "https://repository.rudder.io/rpm/rudder_rpm_key.pub"
