#!/bin/sh

set -e

# Documentation !
usage() {
  echo "Usage $0 [add_repository|setup_agent|setup_server] <rudder_version>"
  echo "  Adds a repository and setup rudder on your OS" 
  echo "  Should work on as many OS as possible"
  echo "  Currently suported : Debian, Ubuntu, RHEL, Fedora, Centos, Amazon, Oracle, SLES"
  exit 1
}
# GOTO bottom for main()

# Reimplement which (taken from 10_ncf_internals/list-compatible-inputs)
_which() {
  name="$1"
  IFS_SAVE="$IFS"
  IFS=:
  for directory in $PATH
  do
    if [ -x "${directory}/${name}" ]
    then
      echo "${directory}/${name}"
      break
    fi
  done
  IFS="$IFS_SAVE"
}

############################################
# Add rudder repository to package manager #
############################################
add_repo() {
  RUDDER_VERSION="$1"

  if [ -x "${apt}" ]
  then
    # Debian / Ubuntu
    apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 474A19E8
    cat > /etc/apt/sources.list.d/rudder.list << EOF
deb http://www.rudder-project.org/apt-${RUDDER_VERSION}/ `lsb_release -cs` main
EOF
    apt-get update
    return
  
  elif [ -x "${yum}" ]
  then
    if [ -f /etc/fedora-release ]
    then
      # Fedora
      OS="FEDORA"
      OSVERSION=$(cat /etc/fedora-release | sed 's/^.* release \([0-9]\+).*$/\1/')
    elif [ -f /etc/redhat-release ]
    then
      # Redhat 
      OS="RHEL"
      OSVERSION=$(cat /etc/redhat-release | sed 's/^.* release \([0-9]\+\).*$/\1/')
    elif [ -f /etc/centos-release ]
    then
      # Centos
      OS="RHEL"
      OSVERSION=$(cat /etc/centos-release | sed 's/^.* release \([0-9]\+\).*$/\1/')
    elif [ -f /etc/oracle-release]
    then
      # Oracle unbreakable linux
      OS="RHEL"
      OSVERSION=$(cat /etc/oracle-release | sed 's/^.* release \([0-9]\+\).*$/\1/')
    elif [ -f /etc/system-release ]
    then
      # Amazon Linux
      if [ "$(awk -F: '{print $3}' /etc/system-release-cpe)" = "amazon" ]; then
        OS="RHEL"
        OSVERSION=$(awk -F: '{print $5}' /etc/system-release-cpe)
      fi
   fi
  
    # Add repo
    if [ -n "${OS}" ]
    then
      cat > /etc/yum.repos.d/rudder.repo << EOF
[Rudder_${RUDDER_VERSION}]
name=Rudder ${RUDDER_VERSION} Repository
baseurl=http://www.rudder-project.org/rpm-${RUDDER_VERSION}/${OS}_${OSVERSION}/
gpgcheck=1
gpgkey=http://www.rudder-project.org/rpm-${RUDDER_VERSION}/${OS}_${OSVERSION}/repodata/repomd.xml.key
EOF
      rpm --import "http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0xADAB3BD36F07D355"
      return
    fi
  
  elif [ -x "${zypper}" ]
  then
    # SLES
    OSVERSION=$(cat /etc/SuSE-release | grep VERSION | cut -f2 -d '=' | sed 's/ //')
    OSSP=$(/etc/SuSE-release | grep PATCHLEVEL | cut -f2 -d '=' | sed 's/ //')
    [ "${OSVERSION}" -eq 10 ] && OSVERSION="${OSVERSION}_${OSSP}"
  
    rpm --import "http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0xADAB3BD36F07D355"
    zypper addrepo -n "Normation RPM Repositories" http://www.rudder-project.org/rpm-${RUDDER_VERSION}/SLES_${OSVERSION}/ Rudder || true
    zypper refresh
    return
  fi
  
  # TODO pkgng emerge pacman smartos
  # There is help in Fusion Inventory lib/FusionInventory/Agent/Task/Inventory/Linux/Distro/NonLSB.pm
  echo "Sorry your Package Manager is not *yet* supported !"
  exit 3
}

######################
# Setup rudder agent #
######################
setup_agent() {
  RUDDER_VERSION="$1"

  if [ -x "${apt}" ]
  then
    export DEBIAN_FRONTEND=noninteractive
    apt-get -y install rudder-agent
  elif [ -x "${yum}" ]
  then
    # TODO rhel5 only
    yum -y install pcre openssl db4-devel
    yum -y install rudder-agent
  elif [ -x "${zypper}" ]
  then
    zypper --non-interactive install rudder-agent
  else
    echo "Sorry your System is not *yet* supported !"
    exit 4
  fi
  # TODO find better settings
  sed -ri "s/^127\.0\.1\.1[\t ]+(node[0-9]+)(.*)/127\.0\.1\.1\\t\1\.rudder\.local\2/" /etc/hosts
  echo -e "\n192.168.42.10 server.rudder.local" >> /etc/hosts
  echo "192.168.42.10" > /var/rudder/cfengine-community/policy_server.dat
  /etc/init.d/rudder-agent start
}

#######################
# Setup rudder server #
#######################
setup_server() {
  RUDDER_VERSION="$1"

  # detect package manager
#  apt=`which apt-get`
#  yum=`which yum`
#  zypper=`which zypper`

#  if [ -x "${apt}" ]
#  then
#  elif [ -x "${yum}" ]
#  then
#  elif [ -x "${zypper}" ]
#  then
#  else
    echo "Sorry your System is not supported by Rudder Server !"
    exit 5
#  fi
}


########
# MAIN #
########

COMMAND="$1"
RUDDER_VERSION="$2"

# detect package manager
apt=`_which apt-get || true`
yum=`_which yum || true`
zypper=`_which zypper || true`

case "${COMMAND}" in
  add_repository)
    add_repo "${RUDDER_VERSION}"
    ;;
  setup_agent)
    add_repo "${RUDDER_VERSION}"
    setup_agent "${RUDDER_VERSION}"
    ;;
  setup_server)
    add_repo "${RUDDER_VERSION}"
    setup_server "${RUDDER_VERSION}"
    ;;
  *)
    usage
    ;;
esac
