#!/bin/sh

PORT=8381
PF=centos
# available: progress, documentation, html, json
FORMAT=documentation

RSPEC_BIN="/usr/bin/ruby2.1 -S rspec"
RSPEC_OPTS="--order defined --fail-fast --format ${FORMAT}"
RSPEC="${RSPEC_BIN} ${RSPEC_OPTS}"

export PATH=$PATH:/home/bpeccatte/Rudder/rudder-api-client/cli
export PYTHONPATH=/home/bpeccatte/Rudder/rudder-api-client/lib.python
export RUDDER_SERVER=https://localhost:${PORT}/rudder
export RUDDER_TOKEN=$(vagrant ssh ${PF}_server -c "sudo cat /root/rudder-token" 2>/dev/null | tr -d '\r')

# Generic tests
TARGET_HOST=${PF}_agent1 ${RSPEC} spec/tests/fusion.rb spec/tests/agent.rb
echo ""
TARGET_HOST=${PF}_server ${RSPEC} spec/tests/fusion.rb spec/tests/agent.rb
echo ""

# force inventory
RUDDER_PARAMS="-D force_inventory" TARGET_HOST=${PF}_agent1 ${RSPEC} spec/tests/run_agent.rb
echo ""
RUDDER_PARAMS="" TARGET_HOST=${PF}_server ${RSPEC} spec/tests/run_agent.rb
echo ""

# accept node
RUDDER_ACCEPT=agent1 TARGET_HOST=localhost ${RSPEC} spec/tests/agent_accept.rb
echo ""

# Add a rule
date0=$(vagrant ssh ${PF}_server -c "date +%s" 2>/dev/null | tr -d '\r')
RUDDER_NAME="Test User" RUDDER_GROUP="special:all" TARGET_HOST=localhost ${RSPEC} spec/tests/user_rule.rb
echo ""

# wait for promise generation
agent_uuid=$(rudder-cli --skip-verify --url=${RUDDER_SERVER} --token=${RUDDER_TOKEN} nodes list | jq '.nodes | map(select(.hostname=="agent1")) | .[0].id' | tr -d '"')
while true
do
  sleep 1
  echo "Waiting for $agent_uuid"
  d1=$(vagrant ssh ${PF}_server -c "sudo cat /var/rudder/share/${agent_uuid}/rules/cfengine-community/rudder_promises_generated 2>/dev/null" | tr -d '\r')
  [ -z "${d1}" ] && break
  date1=$(date -d ${d1} +%s)
  if [ ${date1} -gt ${date0} ]
  then
    break
  fi
done


# Run agent
RUDDER_PARAMS="-f failsafe.cf" TARGET_HOST=${PF}_agent1 ${RSPEC} spec/tests/run_agent.rb
echo ""
RUDDER_PARAMS="" TARGET_HOST=${PF}_agent1 ${RSPEC} spec/tests/run_agent.rb
echo ""

# Test rule result
TARGET_HOST=${PF}_agent1 ${RSPEC} spec/tests/user_test.rb
echo ""


# remove rule/directive
RUDDER_DELETE="Test User Directive" RUDDER_GROUP="special:all" TARGET_HOST=localhost ${RSPEC} spec/tests/directive_delete.rb
echo ""
RUDDER_DELETE="Test User Rule" RUDDER_GROUP="special:all" TARGET_HOST=localhost ${RSPEC} spec/tests/rule_delete.rb
echo ""

# remove agent
RUDDER_DELETE=agent1 TARGET_HOST=localhost ${RSPEC} spec/tests/agent_delete.rb
echo ""
